version: "3.9"
services:
  api:
    build: { context: ., dockerfile: Dockerfile.api }
    env_file: .env
    ports: [ "3000:3000" ]
    depends_on: [ postgres, redis, minio ]
    volumes: [ ".:/app" ]
  worker:
    build: { context: ., dockerfile: Dockerfile.worker }
    env_file: .env
    depends_on: [ postgres, redis, minio ]
    volumes: [ ".:/app" ]
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vyapgo
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    ports: [ "5432:5432" ]
  redis:
    image: redis:7
    ports: [ "6379:6379" ]
    volumes:
      - ./docker-data/redis:/data
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: [ "9000:9000", "9001:9001" ]
    volumes:
      - ./docker-data/minio:/data
